### ISSUE TITLE
gmock segfault if GTEST_HAS_PTHREAD=0 is defined

### ISSUE THREAD

**Issue by mgerhardy** [google/googletest#1651]
```
0x0000555555ea50ba in testing::internal::ThreadLocal<testing::Sequence*>::GetOrCreateValue (this=0x555556abb4e8 <testing::internal::g_gmock_implicit_sequence>)
    at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gtest/internal/gtest-port.h:2205
2205	    ValueHolder* const new_holder = default_factory_->MakeNewHolder();
(gdb) bt
#0  0x0000555555ea50ba in testing::internal::ThreadLocal<testing::Sequence*>::GetOrCreateValue() const (this=0x555556abb4e8 <testing::internal::g_gmock_implicit_sequence>)
    at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gtest/internal/gtest-port.h:2205
#1  0x0000555555ea2c10 in testing::internal::ThreadLocal<testing::Sequence*>::pointer() const (this=0x555556abb4e8 <testing::internal::g_gmock_implicit_sequence>)
    at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gtest/internal/gtest-port.h:2171
#2  0x0000555555ea0964 in testing::internal::ThreadLocal<testing::Sequence*>::get() const (this=0x555556abb4e8 <testing::internal::g_gmock_implicit_sequence>)
    at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gtest/internal/gtest-port.h:2172
#3  0x0000555555e9dea8 in testing::internal::FunctionMockerBase<bool (unsigned int, persistence::ISavable*)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<unsigned int>, testing::Matcher<persistence::ISavable*> > const&) (this=
    0x555556b66000, file=0x55555652f900 "/home/mgerhardy/dev/engine/src/modules/backend/tests/EntityTest.h", line=90, source_text="EXPECT_CALL(*persistenceMgr, registerSavable(::testing::_, ::testing::_))", m=std::tuple containing = {...}) at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gmock/gmock-spec-builders.h:1632
#4  0x0000555555e9b899 in testing::internal::MockSpec<bool (unsigned int, persistence::ISavable*)>::InternalExpectedAt(char const*, int, char const*, char const*) (this=0x7fffffffdcd0, file=0x55555652f900 "/home/mgerhardy/dev/engine/src/modules/backend/tests/EntityTest.h", line=90, obj=0x55555652f974 "*persistenceMgr", call=0x55555652f948 "registerSavable(::testing::_, ::testing::_)")
    at /home/mgerhardy/dev/engine/contrib/libs/gtest/include/gmock/gmock-spec-builders.h:1282
#
```

**Comment by gennadiycivil** [comment]
There is no actionable information here
