### ISSUE TITLE
msan: googletest breaks under MemorySanitizer

### ISSUE THREAD

**Issue by g-easy** [google/googletest#1919]
```shell
git clone https://github.com/google/googletest
cd googletest
env MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-5.0/bin/llvm-symbolizer CC=clang-5.0 bazel run -c dbg --copt -fsanitize=memory --copt -DMEMORY_SANITIZER --linkopt -fsanitize=memory --cc_output_directory_tag=msan :sample10_unittest
[...]
==123989==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f9a01dece95 in testing::internal::StringStreamToString(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) /proc/self/cwd/googletest/src/gtest.cc:2034:9
    #1 0x7f9a01decad4 in testing::Message::GetString[abi:cxx11]() const /proc/self/cwd/googletest/src/gtest.cc:1031:10
    #2 0x7f9a01dc17bf in testing::internal::FlagToEnvVar[abi:cxx11](char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1199:49
    #3 0x7f9a01dc296e in testing::internal::StringFromGTestEnv(char const*, char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1315:31
    #4 0x7f9a01d2dfbf in __cxx_global_var_init.1 /proc/self/cwd/googletest/src/gtest-death-test.cc:89:1
    #5 0x7f9a01d2e37d in _GLOBAL__sub_I_gtest_death_test.cc /proc/self/cwd/googletest/src/gtest-death-test.cc
    #6 0x7f9a01efe8a9  (/lib64/ld-linux-x86-64.so.2+0xf8a9)
    #7 0x7f9a01efe9ba  (/lib64/ld-linux-x86-64.so.2+0xf9ba)
    #8 0x7f9a01eefc59  (/lib64/ld-linux-x86-64.so.2+0xc59)
```

The code in question doesn't seem to be doing anything wrong. Is `std::string` memory poisoned?

**Comment by sbenzaquen** [comment]
Thanks for the report. Unfortunately, I can't reproduce this problem.
Maybe it is somehow related to the standard library you are using? Do you
know which one it is?
Also, you could pass -fsanitize-memory-track-origins which will make msan
give a much more detailed report. That might tell us what the problem is.

**Comment by g-easy** [comment]
I tried again with an up-to-date checkout and I can still reproduce it with the bazel command I posted.

Here it is with origins:

```
env MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-5.0/bin/llvm-symbolizer CC=clang-5.0 bazel run -c dbg --copt -fsanitize=memory --copt -DMEMORY_SANITIZER --copt -fsanitize-memory-track-origins --linkopt -fsanitize=memory --cc_output_directory_tag=msan :sample10_unittest
[...]
Executing tests from //:sample10_unittest
-----------------------------------------------------------------------------
==27426==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa49109112c in testing::internal::StringStreamToString(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) /proc/self/cwd/googletest/src/gtest.cc:2029:9
    #1 0x7fa49109058f in testing::Message::GetString[abi:cxx11]() const /proc/self/cwd/googletest/src/gtest.cc:1026:10
    #2 0x7fa4910246f9 in testing::internal::FlagToEnvVar[abi:cxx11](char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1199:49
    #3 0x7fa491026b42 in testing::internal::StringFromGTestEnv(char const*, char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1315:31
    #4 0x7fa490ea0318 in __cxx_global_var_init.1 /proc/self/cwd/googletest/src/gtest-death-test.cc:94:1
    #5 0x7fa490ea07ad in _GLOBAL__sub_I_gtest_death_test.cc /proc/self/cwd/googletest/src/gtest-death-test.cc
    #6 0x7fa49140b8a9  (/lib64/ld-linux-x86-64.so.2+0xf8a9)
    #7 0x7fa49140b9ba  (/lib64/ld-linux-x86-64.so.2+0xf9ba)
    #8 0x7fa4913fcc59  (/lib64/ld-linux-x86-64.so.2+0xc59)

  Uninitialized value was stored to memory at
    #0 0x42f86d in __msan_memcpy.part.50 (.../execroot/com_google_googletest/bazel-out/k8-msan-dbg/bin/sample10_unittest+0x42f86d)
    #1 0x7fa490b9480d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12180d)

  Uninitialized value was stored to memory at
    #0 0x42f86d in __msan_memcpy.part.50 (.../execroot/com_google_googletest/bazel-out/k8-msan-dbg/bin/sample10_unittest+0x42f86d)
    #1 0x7fa490b9554b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12254b)

  Uninitialized value was created by a heap allocation
    #0 0x42fb41 in __interceptor_malloc (.../execroot/com_google_googletest/bazel-out/k8-msan-dbg/bin/sample10_unittest+0x42fb41)
    #1 0x7fa490b05f6b in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x92f6b)
    #2 0x7fa491024618 in testing::internal::FlagToEnvVar[abi:cxx11](char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1199:8
    #3 0x7fa491026b42 in testing::internal::StringFromGTestEnv(char const*, char const*) /proc/self/cwd/googletest/src/gtest-port.cc:1315:31
    #4 0x7fa490ea0318 in __cxx_global_var_init.1 /proc/self/cwd/googletest/src/gtest-death-test.cc:94:1
    #5 0x7fa490ea07ad in _GLOBAL__sub_I_gtest_death_test.cc /proc/self/cwd/googletest/src/gtest-death-test.cc
    #6 0x7fa49140b8a9  (/lib64/ld-linux-x86-64.so.2+0xf8a9)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/googletest/src/gtest.cc:2029:9 in testing::internal::StringStreamToString(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*)
Exiting
```

**Comment by g-easy** [comment]
Essentially this issue is about: how can I use googletest + msan to test my software?

I've tried to reduce it to a minimal test case where even in the googletest repo, I can't get msan to pass.

https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo seems to be saying that I need to build my own libc++. Is this what googletest does for development? Do you run msan + custom libc++ on Travis?

**Comment by gennadiycivil** [comment]
NOTE:
We are very much open to considering a PR that would add a sanitized build
on Travis.
Thanks

**Comment by gennadiycivil** [comment]
Ping
