### ISSUE TITLE
Bazel tests fail when using Python3

### ISSUE THREAD

**Issue by qzmfranklin** [google/googletest#2001]
# Reproduction

Create the following two files:
```
# tools/python/BUILD
py_runtime(
    name = 'py-3',
    visibility = [
        '//visibility:public',
    ],
    interpreter_path = '/usr/bin/python3',
    files = [],
)
```

```
# bazel.rc
build --python_top=tools/python:py-3
```

Then running `bazel test ...` from the root directory would yield errors similar to the following:
```
FAIL: //third_party/cc/gtest/googletest/test:gtest_throw_on_failure_test (see /home/zhongming/.cache/
bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/testlogs
/third_party/cc/gtest/googletest/test/gtest_throw_on_failure_test/test.log)
INFO: From Testing //third_party/cc/gtest/googletest/test:gtest_throw_on_failure_test:
==================== Test output for //third_party/cc/gtest/googletest/test:gtest_throw_on_failure_te
st:
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-
sandbox/18/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_throw_
on_failure_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_throw_on_failure_test.py", l
ine 73  
    print 'Running "%s". . .' % ' '.join(command)
                            ^
SyntaxError: invalid syntax
================================================================================

(omitted for brevity ...)


FAIL: //third_party/cc/gtest/googletest/test:gtest_output_test (see /home/zhongming/.cache/bazel/_baz
el_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/testlogs/third_par
ty/cc/gtest/googletest/test/gtest_output_test/test.log)
INFO: From Testing //third_party/cc/gtest/googletest/test:gtest_output_test:
==================== Test output for //third_party/cc/gtest/googletest/test:gtest_output_test:
E/usr/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/35/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_output_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_output_test_golden_lin.txt'>
  outcome.errors.clear()

======================================================================
ERROR: testOutput (__main__.GTestOutputTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/35/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_output_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_output_test.py", line 291, in testOutput
    golden = ToUnixLineEnding(golden_file.read())
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/35/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_output_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_output_test.py", line 88, in ToUnixLineEnding 
    return s.replace('\r\n', '\n').replace('\r', '\n')
TypeError: a bytes-like object is required, not 'str'


======================================================================
ERROR: testOutfile1 (__main__.GTestXMLOutFilesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/80/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_xml_outfiles_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_xml_outfiles_test.py", line 101, in testOutfile1
    self._TestOutFile(GTEST_OUTPUT_1_TEST, EXPECTED_XML_1)
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/80/execroot/logi/bazel-out/k8-fastbuild/bin/third_party/cc/gtest/googletest/test/gtest_xml_outfiles_test.runfiles/logi/third_party/cc/gtest/googletest/test/gtest_xml_outfiles_test.py", line 133, in _TestOutFile
    actual.documentElement)
  File "/home/zhongming/git/LogiOcean/third_party/cc/gtest/googletest/test/gtest_xml_test_utils.py", line 97, in AssertEquivalentNodes
    for child_id, child in expected_children.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'


----------------------------------------------------------------------
Ran 1 test in 0.054s

FAILED (errors=1)
================================================================================
```

The issue seems to be that the python tests only work for Python2 but not Python3.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration. You may want to take a look at https://github.com/abseil/googletest/pull/1839 for an example. Thank you again

**Comment by gennadiycivil** [comment]
ping

**Comment by gennadiycivil** [comment]
Looks stale, closing
