### ISSUE TITLE
gmock_gen.py failed

### ISSUE THREAD

**Issue by AZhurkin** [google/googletest#3010]
File rg.h:
`
#ifndef RG
#define RG

#include <cstdint>

class A {
	
public:
	
	virtual int toFloat(float a) = 0;
	
};

#endif`

Python 3.8.2
Command: python gmock_gen.py rg.h

Result:
`Traceback (most recent call last):
  File "gmock_gen.py", line 30, in <module>
    gmock_class.main()
  File "C:\Users\AZhurkin\projects\googletest\googlemock\scripts\generator\cpp\gmock_class.py", line 240, in main
    lines = _GenerateMocks(filename, source, entire_ast, desired_class_names)
  File "C:\Users\AZhurkin\projects\googletest\googlemock\scripts\generator\cpp\gmock_class.py", line 147, in _GenerateMocks
    for node in ast_list:
  File "...\googletest\googlemock\scripts\generator\cpp\ast.py", line 715, in Generate
    token = self._GetNextToken()
  File "...\googletest\googlemock\scripts\generator\cpp\ast.py", line 945, in _GetNextToken
    return next(self.tokens)
  File "...\googletest\googlemock\scripts\generator\cpp\tokenize.py", line 235, in GetTokens
    if source[i] == '"':
IndexError: string index out of range`

**Comment by asoffer** [comment]
The source file rg.h needs to compile for gmock_gen.py to run successfully. It looks like one of your #include statements is incorrect. Please reopen this if you have the same issue with a version of rg.h that compiles.
