### ISSUE TITLE
msys2 gmock / segmentation fault

### ISSUE THREAD

**Issue by franku** [google/googletest#3571]
**Describe the bug**

On windows/msys2 I want to build and execute a small test using gtest and gmock, source code here: https://github.com/franku/msys2-gtest. However everything compiles well the test always ends with segmentation fault. I am not sure if it is a bug or I oversee something. 

**Steps to reproduce the bug**

Install a current msys2 developer environment (i.e. gcc 10.2.0, cmake 3.21.0) and checkout above source code. 
Then run cmake and make, afterwards execute the test binary Battery.exe: 

> Running main() from ./foo/battery/b/_deps/googletest-src/googletest/src/gtest_main.cc
> [==========] Running 2 tests from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 2 tests from Battery
> [ RUN      ] Battery.get_remaining_capacity
> Segmentation fault (core dumped)`

**Does the bug persist in the most recent commit?**

Yes, I tried current master and Release 1.11.0

**What operating system and version are you using?**

I am using msys2 because I need to run it on windows. 

**What compiler and version are you using?**

gcc 10.2.0

**What build system are you using?**

msys2 with cmake 3.21

**Additional context**

I also built gtest from the sources with `make install`, however same problem. I could not yet get the mingw package running in my msys2 installation (https://packages.msys2.org/base/mingw-w64-googletest)

**Comment by franku** [comment]
```
Reading symbols from ./Battery.exe...
(gdb) r
Starting program: /home/f.ueberschar/PowerModul-Software/EclipseCDT/workspace/EnEcmoPowerModule/test/software/battery/b/Battery.exe
[New Thread 12080.0x3154]
[New Thread 12080.0x1c54]
[New Thread 12080.0x3f50]
[New Thread 12080.0x27a8]
[New Thread 12080.0xda8]
Running main() from /home/f.ueberschar/PowerModul-Software/EclipseCDT/workspace/EnEcmoPowerModule/test/software/battery/b/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Battery
[ RUN      ] Battery.get_remaining_capacity

Thread 1 "Battery" received signal SIGSEGV, Segmentation fault.
0x000000010044d032 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy() ()
(gdb) bt
#0  0x000000010044d032 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy() ()
#1  0x000000010044bb09 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) ()
#2  0x000000010044b166 in std::__shared_ptr<testing::internal::ExpectationBase, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<testing::internal::ExpectationBase, (__gnu_cxx::_Lock_policy)2> const&) ()
#3  0x0000000100446350 in std::shared_ptr<testing::internal::ExpectationBase>::shared_ptr(std::shared_ptr<testing::internal::ExpectationBase> const&) ()
#4  0x000000010042b4d0 in testing::Expectation::Expectation(testing::Expectation const&) ()
#5  0x0000000100439f85 in void __gnu_cxx::new_allocator<std::_Rb_tree_node<testing::Expectation> >::construct<testing::Expectation, testing::Expectation const&>(testing::Expectation*, testing::Expectation const&) ()
#6  0x000000010044e246 in void std::allocator_traits<std::allocator<std::_Rb_tree_node<testing::Expectation> > >::construct<testing::Expectation, testing::Expectation const&>(std::allocator<std::_Rb_tree_node<testing::Expectation> >&, testing::Expectation*, testing::Expectation const&) ()
#7  0x00000001004599bc in void std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_M_construct_node<testing::Expectation const&>(std::_Rb_tree_node<testing::Expectation>*, testing::Expectation const&) ()
#8  0x000000010045981f in std::_Rb_tree_node<testing::Expectation>* std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_M_create_node<testing::Expectation const&>(testing::Expectation const&) ()
#9  0x00000001004443f4 in std::_Rb_tree_node<testing::Expectation>* std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_Alloc_node::operator()<testing::Expectation const&>(testing::Expectation const&) const ()
#10 0x000000010045964f in std::_Rb_tree_iterator<testing::Expectation> std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_M_insert_<testing::Expectation const&, std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_Alloc_node>(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, testing::Expectation const&, std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_Alloc_node&) ()
#11 0x0000000100459909 in std::pair<std::_Rb_tree_iterator<testing::Expectation>, bool> std::_Rb_tree<testing::Expectation, testing::Expectation, std::_Identity<testing::Expectation>, testing::Expectation::Less, std::allocator<testing::Expectation> >::_M_insert_unique<testing::Expectation const&>(testing::Expectation const&) ()
#12 0x00000001004505eb in std::set<testing::Expectation, testing::Expectation::Less, std::allocator<testing::Expectation> >::insert(testing::Expectation const&) ()
#13 0x000000010042bad7 in testing::ExpectationSet::operator+=(testing::Expectation const&) ()
#14 0x000000010040648a in testing::Sequence::AddExpectation(testing::Expectation const&) const ()
#15 0x00000001004318e5 in testing::internal::FunctionMocker<unsigned short ()>::AddNewExpectation(char const*, int, std::string const&, std::tuple<> const&) ()
#16 0x0000000100437ee5 in testing::internal::MockSpec<unsigned short ()>::InternalExpectedAt(char const*, int, char const*, char const*) ()
#17 0x000000010042b1df in MockBattery::MockBattery() ()
#18 0x00000001004010b0 in Battery_get_remaining_capacity_Test::TestBody() ()
#19 0x0000000100436eac in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#20 0x0000000100436840 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#21 0x000000010040f8b9 in testing::Test::Run() ()
#22 0x0000000100410155 in testing::TestInfo::Run() ()
#23 0x000000010041092e in testing::TestSuite::Run() ()
#24 0x000000010041e2ce in testing::internal::UnitTestImpl::RunAllTests() ()
#25 0x0000000100436dac in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#26 0x0000000100436420 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#27 0x000000010041cf9d in testing::UnitTest::Run() ()
#28 0x000000010042b145 in RUN_ALL_TESTS() ()
#29 0x000000010040161c in main ()
(gdb)
```

**Comment by franku** [comment]
Solved it using the right mingw toolchain: https://packages.msys2.org/group/mingw-w64-i686-toolchain
(i.e. i686-w64-mingw32-gcc.exe (Rev5, Built by MSYS2 project) 10.3.0)
