### ISSUE TITLE
alloc-dealloc-mismatch when building with clang and libc++

### ISSUE THREAD

**Issue by criatura2** [google/googletest#3998]
Gtest version: 1.12.1
Clang version: 12.0.1-19ubuntu3

Hi, we are getting `alloc-dealloc-mismatch` in our tests when building with `clang`, `libc++` and address sanitizer. I could reduce the problem to the following

```
#include <gtest/gtest.h>
#include <gmock/gmock.h>

struct Foo {
	MOCK_METHOD(int, bar, ());
};

struct SensorTest : ::testing::Test { };

TEST(SensorTest, Accelerometer)
{
	Foo f;
	EXPECT_CALL(f, bar()).WillOnce(::testing::Throw(std::runtime_error("FAILED")));
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```

which we build with something like
```
clang++ test.cpp  -I incdir/googletest/include/ -I incdir/googlemock/include/ libdir/libgmock.a  libdir/libgtest.a -fsanitize=address -stdlib=libc++
```

The error produced looks like this
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SensorTest
[ RUN      ] SensorTest.Accelerometer
Sensor_tests.cpp:13: Failure
Actual function call count doesn't match EXPECT_CALL(f, bar())...
         Expected: to be called once
           Actual: never called - unsatisfied and active
=================================================================
==9==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x6030000005e0
    #0 0x4a1be2 in free (/opt/cinemo/cinemo-ux/a.out+0x4a1be2)
    #1 0x7fbecb3b33fd in std::underflow_error::~underflow_error() (/lib/x86_64-linux-gnu/libc++abi.so.1+0x263fd)
    #2 0x4effb4 in testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'()::~() (/opt/cinemo/cinemo-ux/a.out+0x4effb4)
    #3 0x4f1c94 in std::__1::__compressed_pair_elem<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'(), 0, false>::~__compressed_pair_elem() (/opt/cinemo/cinemo-ux/a.out+0x4f1c94)
    #4 0x4f1db4 in std::__1::__compressed_pair<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'(), std::__1::allocator<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'()> >::~__compressed_pair() (/opt/cinemo/cinemo-ux/a.out+0x4f1db4)
    #5 0x4f3964 in std::__1::__function::__alloc_func<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'(), std::__1::allocator<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'()>, int ()>::destroy() (/opt/cinemo/cinemo-ux/a.out+0x4f3964)
    #6 0x4f0fa8 in std::__1::__function::__func<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'(), std::__1::allocator<testing::internal::ThrowAction<std::runtime_error>::operator testing::Action<int ()><int>() const::'lambda'()>, int ()>::destroy() (/opt/cinemo/cinemo-ux/a.out+0x4f0fa8)
    #7 0x4e729b in std::__1::__function::__value_func<int ()>::~__value_func() (/opt/cinemo/cinemo-ux/a.out+0x4e729b)
    #8 0x4e71c4 in std::__1::function<int ()>::~function() (/opt/cinemo/cinemo-ux/a.out+0x4e71c4)
    #9 0x4d75b4 in testing::Action<int ()>::~Action() (/opt/cinemo/cinemo-ux/a.out+0x4d75b4)
    #10 0x4e85dc in testing::internal::TypedExpectation<int ()>::~TypedExpectation() (/opt/cinemo/cinemo-ux/a.out+0x4e85dc)
    #11 0x4e86b8 in testing::internal::TypedExpectation<int ()>::~TypedExpectation() (/opt/cinemo/cinemo-ux/a.out+0x4e86b8)
    #12 0x4ea026 in std::__1::default_delete<testing::internal::TypedExpectation<int ()> >::operator()(testing::internal::TypedExpectation<int ()>*) const (/opt/cinemo/cinemo-ux/a.out+0x4ea026)
    #13 0x4e9c1b in std::__1::__shared_ptr_pointer<testing::internal::TypedExpectation<int ()>*, std::__1::shared_ptr<testing::internal::ExpectationBase>::__shared_ptr_default_delete<testing::internal::ExpectationBase, testing::internal::TypedExpectation<int ()> >, std::__1::allocator<testing::internal::TypedExpectation<int ()> > >::__on_zero_shared() (/opt/cinemo/cinemo-ux/a.out+0x4e9c1b)
    #14 0x503466 in std::__1::__shared_count::__release_shared() /usr/lib/llvm-12/bin/../include/c++/v1/memory:2501:9
    #15 0x503466 in std::__1::__shared_weak_count::__release_shared() /usr/lib/llvm-12/bin/../include/c++/v1/memory:2543:27
    #16 0x503466 in std::__1::shared_ptr<testing::internal::ExpectationBase>::~shared_ptr() /usr/lib/llvm-12/bin/../include/c++/v1/memory:3233:19
    #17 0x503466 in std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> >::destroy(std::__1::shared_ptr<testing::internal::ExpectationBase>*) /usr/lib/llvm-12/bin/../include/c++/v1/memory:916:15
    #18 0x503466 in void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> > >::destroy<std::__1::shared_ptr<testing::internal::ExpectationBase>, void>(std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> >&, std::__1::shared_ptr<testing::internal::ExpectationBase>*) /usr/lib/llvm-12/bin/../include/c++/v1/__memory/allocator_traits.h:307:13
    #19 0x503466 in std::__1::__vector_base<std::__1::shared_ptr<testing::internal::ExpectationBase>, std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> > >::__destruct_at_end(std::__1::shared_ptr<testing::internal::ExpectationBase>*) /usr/lib/llvm-12/bin/../include/c++/v1/vector:428:9
    #20 0x503466 in std::__1::__vector_base<std::__1::shared_ptr<testing::internal::ExpectationBase>, 
   std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> > >::clear() /usr/lib/llvm-12/bin/../include/c++/v1/vector:371:29
    #21 0x503466 in std::__1::vector<std::__1::shared_ptr<testing::internal::ExpectationBase>, std::__1::allocator<std::__1::shared_ptr<testing::internal::ExpectationBase> > >::clear() /usr/lib/llvm-12/bin/../include/c++/v1/vector:774:17
    #22 0x503466 in testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googlemock/src/gmock-spec-builders.cc:432:26
    #23 0x4d798a in testing::internal::FunctionMocker<int ()>::~FunctionMocker() (/opt/cinemo/cinemo-ux/a.out+0x4d798a)
    #24 0x4d75f4 in Foo::~Foo() (/opt/cinemo/cinemo-ux/a.out+0x4d75f4)
    #25 0x4d5adf in SensorTest_Accelerometer_Test::TestBody() (/opt/cinemo/cinemo-ux/a.out+0x4d5adf)
    #26 0x5c65e1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2599:10
    #27 0x5c65e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2635:14
    #28 0x56cd57 in testing::Test::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2674:5
    #29 0x56f221 in testing::TestInfo::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2853:11
    #30 0x570f86 in testing::TestSuite::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:3012:30
    #31 0x5abb66 in testing::internal::UnitTestImpl::RunAllTests() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:5870:44
    #32 0x5c89c1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2599:10
    #33 0x5c89c1 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2635:14
    #34 0x5aabad in testing::UnitTest::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:5444:10
    #35 0x4d7610 in RUN_ALL_TESTS() (/opt/cinemo/cinemo-ux/a.out+0x4d7610)
    #36 0x4d5e00 in main (/opt/cinemo/cinemo-ux/a.out+0x4d5e00)
    #37 0x7fbecb085d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #38 0x7fbecb085e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #39 0x426f84 in _start (/opt/cinemo/cinemo-ux/a.out+0x426f84)

0x6030000005e0 is located 0 bytes inside of 31-byte region [0x6030000005e0,0x6030000005ff)
allocated by thread T0 here:
    #0 0x4d2f1d in operator new(unsigned long) (/opt/cinemo/cinemo-ux/a.out+0x4d2f1d)
    #1 0x7fbecb41afcf in std::runtime_error::runtime_error(char const*) (/lib/x86_64-linux-gnu/libc++.so.1+0x4afcf)
    #2 0x5c65e1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2599:10
    #3 0x5c65e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2635:14
    #4 0x56cd57 in testing::Test::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2674:5
    #5 0x56f221 in testing::TestInfo::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2853:11
    #6 0x570f86 in testing::TestSuite::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:3012:30
    #7 0x5abb66 in testing::internal::UnitTestImpl::RunAllTests() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:5870:44
    #8 0x5c89c1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2599:10
    #9 0x5c89c1 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:2635:14
    #10 0x5aabad in testing::UnitTest::Run() /opt/cinemo/cinemo-ux/./src/3rdParty/OpenSource/gtest/gtest-HEAD-2021-02-25/googletest/src/gtest.cc:5444:10
    #11 0x4d7610 in RUN_ALL_TESTS() (/opt/cinemo/cinemo-ux/a.out+0x4d7610)
    #12 0x4d5e00 in main (/opt/cinemo/cinemo-ux/a.out+0x4d5e00)
    #13 0x7fbecb085d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/opt/cinemo/cinemo-ux/a.out+0x4a1be2) in free
==9==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==9==ABORTING
```

**Comment by criatura2** [comment]
This issue is causing my github account to be flagged, so github instructed me to close it, how annoying.
