### ISSUE TITLE
[Bug]: Cannot find "jekyll-theme-primer" stylesheet to import when running 'jekyll build' command.

### ISSUE THREAD

**Issue by hwhsu1231** [google/googletest#4417]
### Describe the issue

Recently, I've been studying Jekyll, and trying to use `jekyll build` command to generate an HTML documentation for GoogleTest locally. However, there is an error occurred:

```
Error: Can't find stylesheet to import.
  ╷
1 │ @import "jekyll-theme-primer";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
```

Even though I already runned `gem install jekyll-theme-primer` to install `jekyll-theme-primer`, the error still exists.

```
C:\Users\hwhsu1231>gem install jekyll-theme-primer
Successfully installed jekyll-theme-primer-0.6.0
Parsing documentation for jekyll-theme-primer-0.6.0
Done installing documentation for jekyll-theme-primer after 0 seconds
1 gem installed
```

What happened? What did I miss?

### Steps to reproduce the problem

1. Install Ruby and Jekyll following the [instructions](https://jekyllrb.com/docs/installation/windows/):

   ```
   ridk install
   3
   gem install jekyll bundler
   gem update --system 3.4.22
   ```

2. Git clone GoogleTest repo and run `jekyll build` command:

   ```
   git clone https://github.com/google/googletest.git
   cd googletest
   cd docs
   jekyll build --trace
   ```

See the following logs for details:

* [LOG-1-rdik-install.txt](https://github.com/google/googletest/files/13398771/LOG-1-rdik-install.txt)
* [LOG-2-gem-install-jekyll-and-bundler.txt](https://github.com/google/googletest/files/13398774/LOG-2-gem-install-jekyll-and-bundler.txt)
* [LOG-3-git-clone-and-jekyll-build.txt](https://github.com/google/googletest/files/13398775/LOG-3-git-clone-and-jekyll-build.txt)

### What version of GoogleTest are you using?

b10fad38c4026a29ea6561ab15fc4818170d1c10

### What operating system and version are you using?

Windows 11

### What compiler and version are you using?

None

### What build system are you using?

None

### Additional context

* Ruby version: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]`
* Jekyll version: `jekyll 4.3.2`
* Bundler version: `Bundler version 2.4.22`
* jekyll-theme-primer: `0.6.0`

**Comment by derekmauro** [comment]
We use Jekyll for our documentation, but are not Jekyll experts and don't offer support for Jekyll issues.

**Comment by hwhsu1231** [comment]
@derekmauro 

I think I found a solution to this issue. Mainly do the following changes:

1. modify `docs/_config.toml`
2. add `docs/Gemfile`
3. add `docs/Gemfile.lock`

And all we need to do to build and preview GoogleTest Documentation locally is:

1. Change Directory to `docs/`
2. Run Command: `bundle install`
3. Run Command: `bundle exec jekyll serve`
4. Open Server address in Browser: http://127.0.0.1:4000

Can I submit a PR to solve this issue?

**Comment by marek22k** [comment]
I have the same problem. I would like to build the documentation, but it fails:
```
$ jekyll build
Configuration file: /home/marek/Downloads/googletest/docs/_config.yml
            Source: /home/marek/Downloads/googletest/docs
       Destination: /home/marek/Downloads/googletest/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Deprecation Warning [import]: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import "jekyll-theme-primer";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
    /home/marek/Downloads/googletest/docs/assets/css/style.scss 1:9  root stylesheet
Deprecation Warning [import]: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
2 │ @import "main";
  │         ^^^^^^
  ╵
    /home/marek/Downloads/googletest/docs/assets/css/style.scss 2:9  root stylesheet
Error: Can't find stylesheet to import.
  ╷
1 │ @import "jekyll-theme-primer";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/marek/Downloads/googletest/docs/assets/css/style.scss 1:9  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Can't find stylesheet to import.
                    ------------------------------------------------
      Jekyll 4.4.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-sass-converter-3.1.0/lib/jekyll/converters/scss.rb:181:in 'Jekyll::Converters::Scss#convert': Can't find stylesheet to import. (Jekyll::Converters::Scss::SyntaxError)

          raise SyntaxError, e.message
                ^^^^^^^^^^^^^^^^^^^^^^
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:105:in 'block in Jekyll::Renderer#convert'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Enumerable#reduce'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Jekyll::Renderer#convert'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:84:in 'Jekyll::Renderer#render_document'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:63:in 'Jekyll::Renderer#run'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:572:in 'Jekyll::Site#render_regenerated'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:564:in 'block in Jekyll::Site#render_pages'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:563:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:563:in 'Jekyll::Site#render_pages'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:211:in 'Jekyll::Site#render'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:80:in 'Jekyll::Site#process'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:28:in 'Jekyll::Command.process_site'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:65:in 'Jekyll::Commands::Build.build'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:36:in 'Jekyll::Commands::Build.process'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'block in Jekyll::Command.process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Jekyll::Command.process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:18:in 'block (2 levels) in Jekyll::Commands::Build.init_with_program'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'block in Mercenary::Command#execute'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Mercenary::Command#execute'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in 'Mercenary::Program#go'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary.rb:21:in 'Mercenary.program'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/exe/jekyll:15:in '<top (required)>'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/jekyll:25:in 'Kernel#load'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/jekyll:25:in '<main>'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/ruby_executable_hooks:22:in 'Kernel#eval'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/ruby_executable_hooks:22:in '<main>'
/home/marek/.rvm/gems/ruby-3.4.4/gems/sass-embedded-1.89.0-x86_64-linux-gnu/lib/sass/compiler/host.rb:86:in 'Sass::Compiler::Host#compile_request': Can't find stylesheet to import. (Sass::CompileError)
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/sass-embedded-1.89.0-x86_64-linux-gnu/lib/sass/compiler.rb:171:in 'Sass::Compiler#compile_string'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/sass-embedded-1.89.0-x86_64-linux-gnu/lib/sass/embedded.rb:37:in 'Sass.compile_string'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-sass-converter-3.1.0/lib/jekyll/converters/scss.rb:163:in 'Jekyll::Converters::Scss#convert'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:105:in 'block in Jekyll::Renderer#convert'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Enumerable#reduce'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:104:in 'Jekyll::Renderer#convert'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:84:in 'Jekyll::Renderer#render_document'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/renderer.rb:63:in 'Jekyll::Renderer#run'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:572:in 'Jekyll::Site#render_regenerated'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:564:in 'block in Jekyll::Site#render_pages'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:563:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:563:in 'Jekyll::Site#render_pages'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:211:in 'Jekyll::Site#render'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/site.rb:80:in 'Jekyll::Site#process'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:28:in 'Jekyll::Command.process_site'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:65:in 'Jekyll::Commands::Build.build'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:36:in 'Jekyll::Commands::Build.process'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'block in Jekyll::Command.process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Jekyll::Command.process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:18:in 'block (2 levels) in Jekyll::Commands::Build.init_with_program'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'block in Mercenary::Command#execute'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Array#each'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Mercenary::Command#execute'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in 'Mercenary::Program#go'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/mercenary-0.4.0/lib/mercenary.rb:21:in 'Mercenary.program'
	from /home/marek/.rvm/gems/ruby-3.4.4/gems/jekyll-4.4.1/exe/jekyll:15:in '<top (required)>'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/jekyll:25:in 'Kernel#load'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/jekyll:25:in '<main>'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/ruby_executable_hooks:22:in 'Kernel#eval'
	from /home/marek/.rvm/gems/ruby-3.4.4/bin/ruby_executable_hooks:22:in '<main>'
```
Are there prebuild versions available?
