### ISSUE TITLE
googletests die when run through MemorySanitizer

### ISSUE THREAD

**Issue by NAThompson** [google/googletest#756]
I'm trying to run my unit test suite through MemorySanitizer. However, I've been thwarted by a use-of-uninitialized value in gtest:

```
Uninitialized bytes in __interceptor_strlen at offset 0 inside [0x722000009ed0, 8)
==10194==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7f9888b7f136 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x122136)
#1 0x4a1ad3 in testing::internal::UnitTestImpl::GetTestCase(char const*, char const*, void (*)(), void (*)()) (/home/nthompson/gtest_bug/a.out+0x4a1ad3)
#2 0x4b0477 in testing::internal::UnitTestImpl::AddTestInfo(void (*)(), void (*)(), testing::TestInfo*) (/home/nthompson/gtest_bug/a.out+0x4b0477)
#3 0x49a4cd in testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*) (/home/nthompson/gtest_bug/a.out+0x49a4cd)
#4 0x41dce4 in __cxx_global_var_init.1 /home/nthompson/gtest_bug/main.cpp:6:1
#5 0x41defd in _GLOBAL__sub_I_main.cpp /home/nthompson/gtest_bug/main.cpp
```

Source code which replicates the error:

```
#include <string>
#include <iostream>
#include <gtest/gtest.h>

TEST(this_is, a_test)
{
    EXPECT_EQ(4, 2+2);
}

int main()
{
    std::string s = "hello, world!";
    std::cout << s << std::endl;
}
```

Makefile:

```
$ cat Makefile 
CXX=clang++
CPPFLAGS:= --std=c++14 -g -O0 -Wall -pthread

ifdef MSAN
CPPFLAGS+= -fsanitize=memory -fno-omit-frame-pointer -fPIE
endif

all:
    $(CXX) $(CPPFLAGS) main.cpp -lgtest

check:
    ./a.out

clean:
    rm -f a.out
```

This issue was found in the apt-get version of gtest, and then I replicated it using the HEAD (currently commit d225acc90bc3a8c420a9bcd1f033033c1ccd7fe0). I'm using the following version of clang:

```
$ clang++ -v
clang version 3.9.0 (trunk 264522)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

I'm on Ubuntu 15.10, if that matters for replication.

This is not a high priority issue but I've found so many bugs running my googletest suite through ThreadSanitizer and AddressSanitizer that I feel like I'm really missing something not having MemorySanitizer available.

**Comment by Moeryn** [comment]
I didn't had the same problem, but I have fixed mine with this:

https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
