### ISSUE TITLE
gmock problems with sanitizers

### ISSUE THREAD

**Issue by syslandscape** [google/googletest#825]
Hi,

this is my cmake:

```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_definitions(-g -Wall -Wextra -pedantic)
add_definitions(-fsanitize=address)
add_definitions(-fsanitize=leak)
add_definitions(-fsanitize=undefined)

SET(TEST_NAME util-format)
add_executable(${TEST_NAME} format.cpp)
target_link_libraries(${TEST_NAME} -lasan -lubsan)
target_link_libraries(${TEST_NAME} gtest gmock gtest_main)
add_test(${TEST_NAME} ${TEST_NAME})
```

Here is my actual test, which is empty:

```
#include <string>
#include <vector>
#include <gtest/gtest.h>

TEST(a, b)
{

}
```

Output, when test is linked against `gmock`:

```
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from a
[ RUN      ] a.b
[       OK ] a.b (0 ms)
[----------] 1 test from a (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
ASAN:DEADLYSIGNAL
=================================================================
==2062==ERROR: AddressSanitizer: SEGV on unknown address 0x60d0317ffff2 (pc 0x7f7ea4e95667 bp 0x7fff9f80aff0 sp 0x7fff9f80a760 T0)
    #0 0x7f7ea4e95666  (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x23666)
    #1 0x7f7ea4f351b6 in operator delete(void*) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc31b6)
    #2 0x7f7ea3f45405 in void std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/c++/6/bits/stl_construct.h:93
    #3 0x7f7ea3f44a67 in void std::_Destroy_aux<false>::__destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/c++/6/bits/stl_construct.h:103
    #4 0x7f7ea3f4402f in void std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/c++/6/bits/stl_construct.h:126
    #5 0x7f7ea3f42e63 in void std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&) /usr/include/c++/6/bits/stl_construct.h:151
    #6 0x7f7ea3f421b0 in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() /usr/include/c++/6/bits/stl_vector.h:426
    #7 0x7f7ea2875ede in __cxa_finalize (/lib/x86_64-linux-gnu/libc.so.6+0x35ede)
    #8 0x7f7ea1aa98c2  (/home/xxx/Sources/build/external/googletest/googlemock/gtest/libgtest.so+0x1798c2)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x23666) 
==2062==ABORTING
```

Interesting part is that, after I modify cmake script, and remove `gmock` library, then sanitzer is not reporting the problem

**Comment by ghita** [comment]
Is there any updates on this ?

**Comment by gennadiycivil** [comment]
@ghost  Apologies for  a VERY long wait. Is this still an issue?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by SoftwareApe** [comment]
I'm having the same issue with address sanitizer and the gtest/gmock included in ROS melodic.

Is there any info on which version this was solved in?

**Comment by joselitofilho** [comment]
I'm having the same issue.
